// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Die Prisma-CLI (migrate deploy/dev) braucht die Direktverbindung
    // (Port 5432): über den Transaktions-Pooler (6543) hängt der
    // Advisory Lock und der Vercel-Build läuft in den Timeout.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
